package com.myspace.task_assigning_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DesignProposal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String furnitureName;
	private java.util.List<com.myspace.task_assigning_demo.Part> parts;

	private java.lang.String furnitureType;

	public DesignProposal() {
	}

	public java.lang.String getFurnitureName() {
		return this.furnitureName;
	}

	public void setFurnitureName(java.lang.String furnitureName) {
		this.furnitureName = furnitureName;
	}

	public java.util.List<com.myspace.task_assigning_demo.Part> getParts() {
		return this.parts;
	}

	public void setParts(
			java.util.List<com.myspace.task_assigning_demo.Part> parts) {
		this.parts = parts;
	}

	public java.lang.String getFurnitureType() {
		return this.furnitureType;
	}

	public void setFurnitureType(java.lang.String furnitureType) {
		this.furnitureType = furnitureType;
	}

	public DesignProposal(java.lang.String furnitureName,
			java.util.List<com.myspace.task_assigning_demo.Part> parts,
			java.lang.String furnitureType) {
		this.furnitureName = furnitureName;
		this.parts = parts;
		this.furnitureType = furnitureType;
	}

}