package com.myspace.task_assigning_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Part implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String partName;

	private java.lang.String furnitureName;

	private java.lang.String factory;

	private java.lang.String furnitureType;

	public Part() {
	}

	public java.lang.String getPartName() {
		return this.partName;
	}

	public void setPartName(java.lang.String partName) {
		this.partName = partName;
	}

	public String toString() {
		return "Part: {furnitureName: " + furnitureName + ", furnitureType: " + furnitureType + ", factory: " + factory + ", partName: " + partName + " }";
	}

	public java.lang.String getFurnitureName() {
		return this.furnitureName;
	}

	public void setFurnitureName(java.lang.String furnitureName) {
		this.furnitureName = furnitureName;
	}

	public java.lang.String getFactory() {
		return this.factory;
	}

	public void setFactory(java.lang.String factory) {
		this.factory = factory;
	}

	public java.lang.String getFurnitureType() {
		return this.furnitureType;
	}

	public void setFurnitureType(java.lang.String furnitureType) {
		this.furnitureType = furnitureType;
	}

	public Part(java.lang.String partName, java.lang.String furnitureName,
			java.lang.String factory, java.lang.String furnitureType) {
		this.partName = partName;
		this.furnitureName = furnitureName;
		this.factory = factory;
		this.furnitureType = furnitureType;
	}
}